trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: aqciconnect@2
  displayName: 'Run ACCELQ Automation'
  inputs:
    appURL: 'https://poc.accelq.io/'
    userName: 'sunilkumar.bhuvin@accelq.com'
    apiKey: 'vpkDVzAX-JRqzk9K3aWxiDbpwa30S5V2U3205PjuKsI'
    tenantCode: 'accelqtraining'
    jobId: '105628'