trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: aqciconnect@2
  displayName: 'Run ACCELQ Automation'
  inputs:
    appURL: 'https://poc.accelq.io/'
    userName: 'sunilkumar.bhuvin@accelq.com'
    apiKey: '$(ACCELQ_API_KEY)'
    tenantCode: 'accelqtraining'
    jobId: '105615'